### PR TITLE
bcftools convert --hapsamp

### PR DESCRIPTION
**Pull request by wkretzsch**
Implementation of `bcftools convert --hapsamp`: conversion from VCF to WTCCC style haps/sample format (according to this spec: https://mathgen.stats.ox.ac.uk/genetics_software/shapeit/shapeit.html#hapsample). 

Tested the new option on `test/convert.vcf` and get expected results.

`--haploid2diploid` option runs, but have not tested the results to make sure they are correct.

### CODE REVIEW

**Comment by wkretzsch** [comment]
the `vcf_to_hapsample` function was mostly copied from `vcf_to_haplegendsample`.  One might consider merging the two functions for ease of maintenance, as they both do very similar things...

**Comment by wkretzsch** [comment]
Just saw that there are some testing scripts.  Will add them. Just a sec.

**Comment by wkretzsch** [comment]
ok, now the `--hapsample` option is being tested in `test/test.pl`

**Comment by pd3** [comment]
Thank you Warren, that's great. I'll merge and check sometime later if the code could be reused as you suggested. Cheers

**Pull request merged**
