### PR TITLE
Subset specific TAGS

### PR DESCRIPTION
**Pull request by mh11**
These changes allow to customise the naming of tags and calculation of alleles by providing
- a custom **prefixes** for **tags**
- a list of sample IDs to calculate the **tags** for
## Combined usage (prefix + samples)
By using these options in combination allows the calculation of e.g. **EUR**, **SAS** and *\* EAS*\* samples on the fly.

```
bcftools +fill-tags my.vcf.gz -- \
-S EUR_,my_eur.txt -S NOT_EUR_,^my_eur.txt \
-S SAS_,my_sas.txt \
-S EAS_,my_eas.txt | \
bgzip > my_annotated.vcf.gz
```
## Prefix

Using a prefix **ABC_** all tags (incl. description) will have the prefix added.
e.g. ABC_AN=.., ABC_AC=..,

## Samples
Using a sample list allows the calculation of **TAGS** specific to this group of samples.
e.g. -S my_list.txt

### CODE REVIEW

**Comment by pd3** [comment]
Hi, thank you for this pull request. There is a [related plugin](https://github.com/pd3/bcftools/blob/develop/plugins/aggregate.c) which should be merged with fill-tags at some point. Could you perhaps modify your pull request according to that? It is more general in that it annotates multiple populations simultaneously.

**Comment by mh11** [comment]
Thanks for the suggestion - your related plugin is very similar in this sense. I’ll give it a go to modify the pull request.

**Comment by mh11** [comment]
The latest commit gives you the flexibility to use multiple ID list in different ways (include/exclude) to annotate vcf files with custom headers.

**Comment by pd3** [comment]
Thank you for this. Can you please check the failing tests?

**Comment by mh11** [comment]
Done - checks are updated, additional test added and all passing.

**Comment by pd3** [comment]
Hi, just added a minor improvement in -S initialization (https://github.com/samtools/bcftools/commit/1322e047f9c94def0a650a8617803d9fbdf6258a) and merged. This pull request can be now closed. Thanks for this!

**Pull request closed without merging**
