### PR TITLE
when constraining alleles, skip calls with problems instead of crashing

### PR DESCRIPTION
**Pull request by koelling**
My suggestion for fixing #534 

Seems to work fine and solves my issue, but it would be great if someone could check to make sure there are no unintended consequences!

### CODE REVIEW

**Comment by pd3** [comment]
Hi, thank you for looking at this and for the pull request. We can accept it as a temporary workaround, but could you please make the function return 0 on success and non-zero on error? (I know the code is not consistent in this.) 
We should leave the issue #534 open, ideally the code should not be skipping such records.

**Comment by koelling** [comment]
Okay, I have changed this now to return 0 on success and 1 on failure. I do think this is a bit confusing though, especially since mcall() seems to be returning 0 on failure. Maybe it would be better to include `stdbool.h` and make this return boolean `true` on success and `false` on failure?

**Comment by pd3** [comment]
`mcall()` returns the number of used alleles. So far it was not handling errors and explicitly asking a site to be dropped. Perhaps a negative value should be used instead in such case

**Comment by koelling** [comment]
I copied the approach of returning 0 on error from a bit further below in the function, where you also seem to return 0 if the site is not "callable": https://github.com/koelling/bcftools/blob/313f8b240b00580751db47965154b55e79b3463a/mcall.c#L1479

Happy to change it to -1, but I assume this would require further changes downstream.

**Comment by pd3** [comment]
Yes you are right, sorry. This will require also a change in vcfcall.c, this line will have to be changed from `error` to `continue`.
https://github.com/samtools/bcftools/blob/develop/vcfcall.c#L852

**Comment by koelling** [comment]
Hmm, wouldn't it be better to leave it as `return 0` to keep it consistent with the rest of the mcall() function? There are several other points where you return 0 to skip and move on to the next variant (e.g. when there are too many alleles, or if the CALL_VARONLY flag is set and is_variant is false). Or would you like me to change all of these to -1?

**Comment by pd3** [comment]
If it is changed, it would need to be done properly throughout the function. But if you don't feel like it, you can leave it to us. Thanks

**Comment by koelling** [comment]
No worries, I am happy to make the changes! One more question though: In vcfcall.c you do some additional handling of the return value depending on whether you are in gvcf mode or not:
https://github.com/samtools/bcftools/blob/develop/vcfcall.c#L852

In particular, if mcall returns zero you might still write it to the file if gvcf mode is on. So if I simply changed mcall() to always `return -1` on error and add a `if(ret == -1) continue;`, to vcfcall.c, this would change the output for gvcfs.

So maybe mcall() should still return 0 for sites that are okay in principle but just not a variant (nAC is zero or out_als is 1), while it should return -1 if the site falls for some reason (too many alleles/cannot constrain)?

Let me know if you agree and I will make the changes.

**Pull request closed without merging**
