### PR TITLE
Fixes the python plotting routines.

### PR DESCRIPTION
**Pull request by sschmeier**
Small changes to the plotting routines in python that will fix some issues with newer python versions.

### CODE REVIEW

**Comment by pd3** [comment]
Thank you

**Comment by jmarshall** [comment]
Note that this was merged to **master**. It might be good to merge/cherry-pick it onto **develop** as well, so that the change is exercised and there are no surprises later.

**Comment by pd3** [comment]
I did not notice, thanks.

**Comment by jmarshall** [comment]
It's a very easy thing to miss :smile: I only noticed because `git fetch` reported that **master** had moved too.

**Pull request merged**
