### PR TITLE
Add test for splitting and merging in one go

### PR DESCRIPTION
**Pull request by jpiper**
I saw that support for for splitting and normalising in one go was introduced in c982c86a7b8fdcd4beff9bb3f7a4fc77e88f0d1a

But there has been no test created for this. I created the `norm.split.and.norm.out` test output with

```
$ ../bcftools norm -m- norm.split.vcf > temp.vcf
$ ../bcftools norm -f norm.fa temp.vcf | grep -v '^##bcftools_' > norm.split.and.norm.out
$ rm temp.vcf
```

### CODE REVIEW

**Comment by jmarshall** [comment]
It's a good test to add, but I don't understand why there are so many differences between _norm.split.out_ and your _norm.split.and.norm.out_.  @pd3, does this point to other bugs?

* At 1:105, shouldn't _norm.split.out_ also have the trimmed alleles (after the fixing of #84)?
* How has _norm.split.and.norm.out_ ended up with two versions of 2:101?

**Comment by jpiper** [comment]
This is odd. So the input line is

    2	101	.	ATTTTTTTTTTTTT	ATTTTTTTTTTTTTTT	999	PASS	INDEL;AN=4;AC=4	GT:DP	1/1:1	1/1:1

When you run

    $ ../bcftools norm -f norm.fa norm.split.vcf

you get

    2	101	.	A	ATT	999	PASS	INDEL;AN=4;AC=4	GT:DP	1/1:1	1/1:1

and when you run

    $ ../bcftools norm -m- norm.split.vcf

you get

    2	101	.	ATTTTTTTTTTTTT	ATTTTTTTTTTTTTTT	999	PASS	INDEL;AN=4;AC=4	GT:DP	1/1:1	1/1:1

which is the same as the input. However, when you pip them together as

    $ ../bcftools norm -m- norm.split.vcf | ../bcftools norm -f norm.fa

You get 

    2	101	.	A	ATT	999	PASS	INDEL;AN=4;AC=4	GT:DP	1/1:1	1/1:1
    2	101	.	A	AT	999	PASS	INDEL;AN=4;AC=2	GT:DP	0/1:1	0/1:1

**Comment by jpiper** [comment]
I can also confirm that this bug exists using  `Version: 1.2 (using htslib 1.2.1)`

    $ bcftools norm -m- norm.split.vcf | bcftools norm -f norm.fa

returns

    2	101	.	A	ATT	999	PASS	INDEL;AN=4;AC=4	GT:DP	1/1:1	1/1:1
    2	101	.	A	AT	999	PASS	INDEL;AN=4;AC=2	GT:DP	0/1:1	0/1:1

**Comment by jpiper** [comment]
To make this even more interesting, `vt normalize` also has the same issue when attempted to normalise this file after splitting. I also tried splitting with `vt decompose` and the issue persists.

I've tracked it down to the following. After splitting `norm.split.vcf` you get this file.

```##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##INFO=<ID=INDEL,Number=0,Type=Flag,Description="Indicates that the variant is an INDEL.">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Phred-scaled likelihood">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Depth">
##contig=<ID=1,length=2147483647>
##contig=<ID=2,length=2147483647>
##contig=<ID=20,length=2147483647>
##contig=<ID=21,length=2147483647>
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=XRF,Number=R,Type=Float,Description="Test Number=AGR in INFO">
##INFO=<ID=XAF,Number=A,Type=Float,Description="Test Number=AGR in INFO">
##INFO=<ID=XGF,Number=G,Type=Float,Description="Test Number=AGR in INFO">
##INFO=<ID=XRI,Number=R,Type=Integer,Description="Test Number=AGR in INFO">
##INFO=<ID=XAI,Number=A,Type=Integer,Description="Test Number=AGR in INFO">
##INFO=<ID=XGI,Number=G,Type=Integer,Description="Test Number=AGR in INFO">
##INFO=<ID=XRS,Number=R,Type=String,Description="Test Number=AGR in INFO">
##INFO=<ID=XAS,Number=A,Type=String,Description="Test Number=AGR in INFO">
##INFO=<ID=XGS,Number=G,Type=String,Description="Test Number=AGR in INFO">
##FORMAT=<ID=FRF,Number=R,Type=Float,Description="Test Number=AGR in FORMAT">
##FORMAT=<ID=FAF,Number=A,Type=Float,Description="Test Number=AGR in FORMAT">
##FORMAT=<ID=FGF,Number=G,Type=Float,Description="Test Number=AGR in FORMAT">
##FORMAT=<ID=FRI,Number=R,Type=Integer,Description="Test Number=AGR in FORMAT">
##FORMAT=<ID=FAI,Number=A,Type=Integer,Description="Test Number=AGR in FORMAT">
##FORMAT=<ID=FGI,Number=G,Type=Integer,Description="Test Number=AGR in FORMAT">
##FORMAT=<ID=FRS,Number=R,Type=String,Description="Test Number=AGR in FORMAT">
##FORMAT=<ID=FAS,Number=A,Type=String,Description="Test Number=AGR in FORMAT">
##FORMAT=<ID=FGS,Number=G,Type=String,Description="Test Number=AGR in FORMAT">
##FORMAT=<ID=FSTR,Number=1,Type=String,Description="Test String in FORMAT">
##INFO=<ID=ISTR,Number=1,Type=String,Description="Test String in INFO">
##bcftools_normVersion=1.2-123-g590b697+htslib-1.2.1
##bcftools_normCommand=norm -m- ../norm.split.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	XY00001	XY00002
1	105	.	TAAACCCTAAA	TAA	999	PASS	INDEL;AN=4;AC=2;DP=19;ISTR=SomeString;XRF=1e+06,2e+06;XRI=1111,2222;XRS=AAA,BBB;XAF=1e+06;XAI=1111;XAS=AAA;XGF=1e+06,2e+06,3e+06;XGI=1111,2222,3333;XGS=A,B,C	GT:PL:DP:FRF:FRI:FRS:FAF:FAI:FAS:FGF:FGI:FGS	1/0:1,2,3:1:1e+06,2e+06:1111,2222:AAAA,BBB:1e+06:1111:A:1e+06,2e+06,3e+06:1111,2222,3333:A,BB,CCC	1/0:1,2,3:1:1e+06,2e+06:1111,2222:AAAA,BBB:1e+06:1111:A:1e+06,2e+06,3e+06:1111,2222,3333:A,BB,CCC
1	105	.	TAAACCCTAAA	TAACCCTAAA	999	PASS	INDEL;AN=4;AC=2;DP=19;ISTR=SomeString;XRF=1e+06,500000;XRI=1111,5555;XRS=AAA,DDD;XAF=500000;XAI=5555;XAS=DDD;XGF=1e+06,500000,9e+09;XGI=1111,5555,9999;XGS=A,E,F	GT:PL:DP:FRF:FRI:FRS:FAF:FAI:FAS:FGF:FGI:FGS	0/1:1,4,6:1:1e+06,500000:1111,5555:AAAA,CC:500000:5555:BB:1e+06,500000,9e+09:1111,5555,9999:A,EEEE,FFFFF	0/1:1,4,6:1:1e+06,500000:1111,5555:AAAA,CC:500000:5555:BB:1e+06,500000,9e+09:1111,5555,9999:A,EEEE,FFFFF
2	1	.	GGGCGTCTCATAGCTGGAGCAATGGCGAGCGCCTGGACAAGGGAGGGGAAGGGGTTCTTATTACTGACGCGGGTAGCCCCTACTGCTGTGTGGTTCCCCTATTTTTTTTTTTTTCTTTTTGAGACGGAGTCTCGCTCTGTCACCCAGGCTGGAGTGCAGTGGCACAATCTCGGCTCACTGCAAGCTCCACCT	ACGT	999	PASS	INDEL;AN=4;AC=2	GT:DP	1/0:1	1/0:1
2	101	.	ATTTTTTTTTTTTT	ATTTTTTTTTTTTTTT	999	PASS	INDEL;AN=4;AC=4	GT:DP	1/1:1	1/1:1
2	114	.	TC	TTCC	999	PASS	INDEL;AN=4;AC=2	GT:DP	1/0:1	1/0:1
2	114	.	TC	TTC	999	PASS	INDEL;AN=4;AC=2	GT:DP	0/1:1	0/1:1
2	115	.	C	T	999	PASS	INDEL;AN=4;AC=4	GT:DP	1/1:1	1/1:1
20	3	.	G	CT	999	PASS	INDEL;AN=4;AC=2	GT	0/1	0/1
20	3	.	GATG	GACT	999	PASS	INDEL;AN=4;AC=2	GT	1/0	1/0
20	5	.	TGGG	TAC	.	PASS	INDEL;AN=4;AC=2	GT:PL:DP	1/0:1,2,3:1	1/0:1,2,3:1
20	5	.	TGGG	TG	.	PASS	INDEL;AN=4;AC=2	GT:PL:DP	0/1:1,4,6:1	0/1:1,4,6:1
20	5	.	TGGG	TGGGG	.	PASS	INDEL;AN=4;AC=0	GT:PL:DP	0/0:1,7,10:1	0/0:1,7,10:1
20	5	.	TGGG	AC	.	PASS	INDEL;AN=4;AC=0	GT:PL:DP	0/0:1,11,15:1	0/0:1,11,15:1
20	59	.	AG	.	999	PASS	AN=4	GT:PL:DP	0/0:0:4	0/0:0:4
20	80	.	CACAG	CACAT	999	PASS	AN=4;AC=2	GT:PL:DP	0/1:255,0,255:13	0/1:255,0,255:13
20	81	.	A	C	999	PASS	AN=4;AC=2	GT:PL:DP	0/1:255,0,255:13	0/1:255,0,255:13
20	95	.	TCACCG	ACACCG	999	PASS	AN=4;AC=2	GT:PL:DP	0/1:255,0,255:13	0/1:255,0,255:13
20	95	.	TCACCG	AAAAAA	999	PASS	AN=4;AC=2	GT:PL:DP	0/1:255,0,255:13	0/1:255,0,255:13
20	273	.	CAAAAAAAAAAAAAAAAAAAAA	CAAAAAAAAAAAAAAAAAAAAAAA	999	PASS	INDEL;AN=4;AC=2	GT:PL:DP	1/0:0,3,5:1	1/0:0,3,5:1
20	273	.	CAAAAAAAAAAAAAAAAAAAAA	CAAAAAAAAAAAAAAAAAAAAAAAA	999	PASS	INDEL;AN=4;AC=2	GT:PL:DP	0/1:0,3,5:1	0/1:0,3,5:1
20	274	.	AAAAAAAAA	AAAAAAAAAAAAAAAAAAA	999	PASS	INDEL;AN=0;AC=0	GT:PL:DP	./.:0,0,0:0	./.:0,0,0:0
20	275	.	A	C	999	PASS	INDEL;AN=2;AC=0	GT:PL:DP:FGF:FGI:FGS:FSTR	0:0,0:0:1e+06,2e+06:1111,2222:A,BB:WORD	0:0,0:0:1e+06,2e+06:1111,2222:A,BB:WORD
20	275	.	A	G	999	PASS	INDEL;AN=2;AC=2	GT:PL:DP:FGF:FGI:FGS:FSTR	1:0,0:0:1e+06,3e+06:1111,3333:A,CCC:WORD	1:0,0:0:1e+06,3e+06:1111,3333:A,CCC:WORD
20	278	.	AAAAAAAAAAAAAAAAA	AAAAAAAAAAAAAAAAAAA	999	PASS	INDEL;AN=0;AC=0	GT:PL:DP	./.:0,0,0:0	./.:0,0,0:0
20	300	.	T	C	999	PASS	INDEL;AN=0;AC=0	GT:PL:DP	./.:0,0,0:0	./.:0,0,0:0
20	300	.	T	G	999	PASS	INDEL;AN=0;AC=0	GT:PL:DP	./.:0,0,0:0	./.:0,0,0:0
21	1	id	TTTA	TTTATTATTA	999	PASS	INDEL;AN=0;AC=0	GT:DP	./.:0	./.:0
21	1	id	TTTA	TTTATTATTATTATTATTATTA	999	PASS	INDEL;AN=0;AC=0	GT:DP	./.:0	./.:0
21	1	id	TTTA	T	999	PASS	INDEL;AN=0;AC=0	GT:DP	./.:0	./.:0
21	1	id	TTTA	TTATTATTA	999	PASS	INDEL;AN=0;AC=0	GT:DP	./.:0	./.:0
```

However, if you remove this record

    2	114	.	TC	TTC	999	PASS	INDEL;AN=4;AC=2	GT:DP	0/1:1	0/1:1

The problem disappears and you don't get duplicates at `2 101`

**Comment by jpiper** [comment]
Oh, and the icing on the cake - if you add more

    2	114	.	TC	TTC	999	PASS	INDEL;AN=4;AC=4	GT:DP	1/1:1	1/1:1

lines you get more duplications at pos `2 101`

**Comment by jpiper** [comment]
Solved it!

    2	114	.	TC	TTC

Is the same as

    2	101	.	A	AT

After normalisation

With the `norm.fa` in that file.

And with regards to 'At 1:105, shouldn't norm.split.out also have the trimmed alleles (now that #84 is fixed)?'

No, because the norm.split test doesn't use the FASTA file, so it's just splitting and not normalising.

**Comment by jmarshall** [comment]
Thanks, I've merged this now.

There would appear to be an opportunity for us to document that `norm` doesn't trim alleles without the `‑f` option (even though in this case at least it would seem that it would be able to do that) :smile:

**Pull request merged**
