### PR TITLE
transcript select for mane and pick in split-vep

### PR DESCRIPTION
**Pull request by barslmn**
I copy-pasted from the CANONICAL selection.
Only difference is with matching the mane transcript where there is additional function call to strncpy for matching "NM".

### CODE REVIEW

**Comment by pd3** [comment]
Thank you for the pull request. Before it can be considered, the test suite must pass and tests for this new functionality added.

**Comment by barslmn** [comment]
Hi, tests are passing. 

This functionality does depend on the vep command being used having the `--pick` parameter. As well as the reference genome since hg19 wont have the mane select.

**Comment by pd3** [comment]
Thank you, it looks good at a brief glance. It will still need a test case before it can be merged.

**Comment by barslmn** [comment]
I can supply test cases and write the tests. Would you direct me where do I put these tests or any guidelines? I only see the data files under test/ dir.

**Comment by pd3** [comment]
Actually, don't worry about it, I will add the tests myself. I just got a similar request and realized it will be better to turn this into something more general, based on regular expressions. I will do that, adding your 'pick' and 'mane' functionality as presets.

**Comment by barslmn** [comment]
Thanks a lot

**Comment by pd3** [comment]
This has been now implemented in https://github.com/samtools/bcftools/commit/944fc9339f441f25c879170aaa7dc530e55d7d9b

**Pull request closed without merging**
