### PR TITLE
Mpileup speedup

### PR DESCRIPTION
**Pull request by jkbonfield**
Speeds up some of the mpileup functions directly (Mann Whitney and cdf functions).  Also uses the pileup callback mechanism (see https://github.com/samtools/htslib/pull/398) to cache the sample ID, avoiding repeated querying of the RG tags.

It's around 20% faster overall.

The large (20x plus) speed gains for PacBio aren't in this version; they didn't speed up when -f was used so are less beneficial than I realised, plus I couldn't see where the analogous code was in the revamped pileup.

### CODE REVIEW

**Comment by mcshane** [comment]
@jkbonfield I think if you rebase this, James, tests should pass now that the corresponding htslib PR is merged.

**Comment by jkbonfield** [comment]
I got lots of conflicts in things I haven't touched.  Has this repository reset at some point?

I can produce a patch of just the two commits I made and apply them to a new develop branch I guess.

**Comment by jkbonfield** [comment]
Ok I think I understand now.  (As instructed) the original branch was off feature/mpileup, but that itself has been rebased before landing in develop. 

I made a new branch from the latest develop and cherry picked in the changes again which went cleanly (unlike rebase).  Hopefully it's all working now.

**Comment by mcshane** [comment]
Merged as cf3a55a4f1ba67a51b6a426fe50b748859783f18

**Comment by jmarshall** [comment]
New file _mw.h_ needs copyright and licensing boilerplate.

**Comment by jkbonfield** [comment]
Good spot John.  Assuming I also have commit access to bcftools I'll add one.

**Pull request closed without merging**
